server:
  port: 8090
  servlet:
    context-path: /security
spring:
  liquibase:
    change-log: liquibase/changelog-master.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security
    username: AccountTest
    password: 1234567890